<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html>
<head>
    <title>Hello JSP</title>
</head>
<body>
    <h1>Hello, JSP!</h1>
    <%
        String message = "This is a dynamic content generated by JSP.";
        out.println(message);
    %>
</body>
</html>
